[tool.poetry]
name = "django-pgschemas"
version = "0.1.0"
description = "Multi-tenancy on Django using Postgres schemas."
authors = ["Lorenzo Peña <lorinkoz@gmail.com>"]
repository = "https://github.com/lorinkoz/django-pgschemas"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Framework :: Django",
    "Framework :: Django :: 2.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.5"
django = "^2.0"
psycopg2-binary = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120
