[tool.poetry]
name = "django-pgschemas"
version = "0.1.1"
description = "Multi-tenancy on Django using PostgreSQL schemas."
license = "MIT"
authors = ["Lorenzo Peña <lorinkoz@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/lorinkoz/django-pgschemas"
documentation = "https://django-pgschemas.readthedocs.io/"
keywords = ["django", "postgresql", "tenants", "schemas", "multi-tenancy"]
classifiers = [
    "Development Status :: 3 - Alpha",
]

[tool.poetry.dependencies]
python = "^3.5"
django = "^2.0"
psycopg2-binary = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
sphinx = "^1.8"
doc8 = "^0.8.0"
sphinx_rtd_theme = "^0.4.2"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
